apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: voting-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-app
  template:
    metadata:
      labels:
        app: result-app
    spec:
      containers:
      - name: result
        image: docker.io/dockersamples/examplevotingapp_result

