apiVersion: v1
kind: Service
metadata:
  name: result-srv
  labels:
    app: voting-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30020
  selector:
    app: result-app
      
