apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: voting-demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: vote
        image: docker.io/dockersamples/examplevotingapp_vote
        ports:
        - containerPort: 80

