apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: voting-demo

spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker
        image: docker.io/dockersamples/examplevotingapp_worker

