apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs-error
  labels:
    app: nginx-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app-error
    spec:
      containers:
      - name: nginx
        image: nginx


  
