apiVersion: v1
kind: Service
metadata:
  name: whiteboard-srv
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
  selector:
    app: whiteboard-app
      
