# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-2.1.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-12-01T13:37:18Z"
  labels:
    app: trustingpanini
  name: trustingpanini
spec:
  containers:
  - env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: NODE_VERSION
      value: 12.20.0
    - name: containers
      value: podman
    - name: YARN_VERSION
      value: 1.22.5
    - name: NODE_ENV
      value: prod
    - name: HOSTNAME
    image: docker.io/rofl256/whiteboard:latest
    name: trustingpanini
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    workingDir: /opt/app
status: {}
---
metadata:
  creationTimestamp: null
spec: {}
status:
  loadBalancer: {}

