apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp-color
  name: webapp-color
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-color
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp-color
    spec:
      containers:
      - image: kodekloud/webapp-color
        name: webapp-color
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: webapp-color-cfg
        # env:
        #- name: APP_COLOR
        #  value: green
        resources: {}
status: {}
