apiVersion: v1
kind: Service
metadata:
  labels:
    name: hippo
    pg-cluster: hippo
    vendor: crunchydata
  name: hippo-svc
  namespace: hippo
spec:
  ports:
  - name: sshd
    port: 2022
    protocol: TCP
    targetPort: 2022
    nodePort: 30022
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
    nodePort: 30432
  selector:
    pg-cluster: hippo
    role: master
  type: NodePort
