apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-operator
  name: postgres-operator-svc
  namespace: pgo
spec:
  ports:
  - name: apiserver
    port: 8443
    protocol: TCP
    targetPort: 8443
    nodePort: 30443
  - name: nsqadmin
    port: 4171
    protocol: TCP
    targetPort: 4171
    nodePort: 30171
  - name: nsqd
    port: 4150
    protocol: TCP
    targetPort: 4150
    nodePort: 30150
  selector:
    name: postgres-operator
  type: NodePort
